---
title: "Adaptation of Staigler et al's Composite Method"
author: "James Henderson"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: cosmo
---

## Staigler et al Adapation

### Preliminaries and notation
The basic algorithm suggested by Staigler et al consists of the following
steps for creating composites of quality measures using multivariate shrinkage. 

In the basic setup, $O_{ijk}$ is the outcome on a binary quality measure $k$ 
for person $j$ in cluster $i$. In our adaptation, clusters will be defined
as subgroups within health care plans. When needed we will denote the subgroup
and plan corresponding to cluster $i$ by $g(i)$ and $p(i)$, respectively.  

Let $K$ be the number of measures and $n_c$ the number of clusters. Let $n_i$
be the number of unique individuals in cluster $i$ and $n_i(k)$ the number in 
the subset contributing to measure $k$. Finally, let $N = \sum_i n_i$ be the
total number of unique individuals and $N(k) = \sum_i n_i$(k)$ the total for
measure $k$. 

### Overview

1. **Estimate risk adjusted cluster-level means for each measure.**  
    1. Let $p_{ijk}(x_{ij}) = \mathbb{P}[O_{ijk} = 1 | X_{ij} = x_{ij}]$ and
     estimate $p_{ijk}$ with
     $\hat{p}_{ijk}(x_{ij})$ using logistic regression or another method.  
    1. Let $E_{ik} = \frac{1}{n_{ik}} \sum_j \hat{p}_{ijk}$,
     $O_{ik} = \frac{1}{n_{ik}} \sum_j \hat{p}_{ijk}$ and
     $Y_{ik} = O_{ik} / E_{ik}$.  
1. **Estimate the within cluster sampling variance.**
  $V_i \in \mathbb{R}^{k \times k}$.  
1. **Estimate cluster-level predictions.**
    1. In the original,
    $\mu_{i}(z_i) := \mathbb{E}[Y_{i\cdot} | Z_i = z_i] = z_i\beta$.  
    1. In our adapation,
    $\mu_{i} := \mathbb{E}[Y_{i\cdot}] = \beta_0 + \eta_{p(i)} + \gamma_i$. 
1. **Estimate the variance-covariance of the cluster-level means.**
   $\Sigma := \mathbb{V}[\mu_{i}] \in \mathbb{R}^{k \times k}$. 
1. **Compute weights.** $W_i := \left(\hat{\Sigma} + \hat{V}_{i}\right)$.
1. **Compute risk-adjusted composites.**
   $\Theta_i := Y_i W_i + \hat{\mu}_i (I - W_i)$. 

### Estimating $V_i$

For each cluster (plan + subgroup) $i$, $V_i$ is the sampling 
variance-covariance of the risk-adjusted estimates $Y_i$. Estimate $V_i$
using the steps below.

1. For each measure, compute residuals $r_{ijk} = y_{ijk} - \hat{p}_{ijk}$.  
1. Mean center $r_{ijk}$ within each cluster,
$\tilde r_{ijk} = r_{ijk} - \frac{1}{n_i(k)}\sum_j r_{ijk}$. If any clusters
have fewer than 2 individuals contributing to measure $k$, set $r_{ijk}$ to
missing and let $n_c(k) := \sum_i 1[n_i(k) \gt 1]$ count the number of effective
clusters with 2 or more individuals contributing to measure $k$. 
1. Let $R_i \in \mathbb{R}^{n_i \times K}$ be a matrix/dataframe where,
the element in row $j$ and column $k$, $R_i(j, k)$ is missing if person $j$ in
cluster $i$ isn't measured on item $k$ and equals $\tilde r_{ijk}$ otherwise.
Stack the $R_i$ to form $R \in \mathbb{R}^{N \times K}$. $R$ is a residual
matrix mean-centered for each measure within each cluster. 
1. Use pairwise complete observations to estimate a variance-covariance matrix
$U \in \mathbb{R}^{k \times k}$.  
1. Adjust elements of $U$ to account for the extra degrees of freedom used
to mean center $\tilde r_{ijk}$ within hospital. Let $S$ be a scaling matrix. 
Along the diagonal, the variance $U_{kk}$ is estimated by $N(k)$ 
individuals. The corresponding scaling factor is
$S_{kk} = \frac{N(k) - 1}{N{k} - n_c(k) + 1}$. For $S_{kk'}$ count
the number of pairwise complete observations and call it $N(k, k')$ and then
let $S_{kk'} = S_{k'k} = \frac{N(k, k') - 1}{N(k,k') - n_c(k, k') + 1}$. Let
$n_c(k, k') = \min(n_c(k), n_c(k'))$.  
1. Let $E_i$ be a $K$-vector of the one over the expected outcomes used to 
normalize $O_i$ to $Y_i$ and let $E_i$ be the $K \times K$ matrix formed by the 
outer product $E_iE_i'$.  
1. Let $N_i$ be a $K \times K$ matrix with
$N_i(k, k') = \frac{1}{\sqrt{n_i(k)n_i(k')}}$.
1. For each $i$, computed $V_i = U_i * S_i * E_i * N_i$ where $*$ is 
element-wise multiplication. 

### Estimating $\mu_i$

In the original, the cluster-level means are estimated using structural
predictions. In our adapation, we are propsing to use shrinkage estimates in 
which subgroups are shrunk toward the plan-level mean and plans are shrunk
toward the grand mean. 

Using the full data, we would propose to estimate a mixed model with plan-level
random intercepts and subgroup-level deviations from the plan mean.  

$$
\mathbb{E}[Y_{ij}] = \beta_0 + \eta_{p(i)} + \gamma_{i},
$$

with $\eta \perp \gamma$ and 

$$
\eta_p \sim_{iid} N(0, \sigma^2_\eta), \gamma_i \sim_{iid}N(0, \sigma^2_\gamma).
$$


Then, estimate 
$\hat{\mu}_i = \hat{\beta}_0 + \hat{\eta}_{p(i)} + \hat{\gamma}_i$
where $\hat{\eta}_p$ and $\hat{\gamma}_i$ are BLUPs.

Computationally, this will
be much more expensive than a model using the weighted cluster-level means as
in the original approach.

*Note.* Potentially, we could estimate the model above using only cluster-level
means and variances. I think this would be an approximation rather than exact,
but  would be an option if this model is computationally intractable.    

### Estimating $\Sigma$

The measure-level variance covariance $\Sigma$ is estimated using residuals
from the model estimating the cluster-level means, $mu_i$. 

In the original, the estimator is defined as,

$$
\tilde \Sigma_{k,k'} = 
  \frac{1}{n_c} \sum_i (Y_i - \hat{\mu}_i)(Y_i - \hat{\mu}_i)' - V_i.  
$$

There is, however, a follow on note about weighting the estimation. If I am
correctly interpreting this note the weights are the product of the sample
sizes for two measures. 

$$
\tilde{\Sigma} = \frac{1}{\sum_i n_i(k)n_i(k')} 
  \sum_i n_i(k)n_i(k') (
    (Y_i(k) - \hat{\mu}_i(k))(Y_i(k') - \hat{\mu}_i(k')) - V_{i}(k,k')
  ).  
$$

There is the potential that the above estimator $\tilde{\Sigma}$ will not be
positive definite. Let $\hat{\Sigma}$ be the nearest positive definite matrix. 
In R, there is a function `Matrix::nearPD()` that will do this. If you need to
do this elsewhere, a simplified way to do this is to estimate the eigen
decomposition (or singular-value decomposition), find the smallest negative
eigenvalue, add it's absolute value plus a small margin (e.g. 0.001) to all
the eigenvalues and then reform the matrix.  

*Note.* One potential improvement over the current proposed adapation would be
to estimate $\mu_i$ and $\Sigma$ in the same step above.  
